export interface ComprobanteDian {
  secuencia: number;
  ned_cab_lote: number;
  empleado: number;
  consecutivo: number;
  marcacion: string;
  compdian_anterior_ajuste: number | null;
  cune: string | null;
  respuesta_xml: string | null;
  fechapago: string;
  prefijo: string;
  numerocomprobantedian: string;
  devengadototal: number;
  deducidototal: number;
  redondeototal: number;
  comprobantetotal: number;
  sueldotrabajado: number;
  diaslaborados: number;
  aux_transporte: number;
  manu_aloja_salarial: number;
  manu_aloja_nosalarial: number;
  hora_ed: number;
  hora_en: number;
  hora_rn: number;
  hora_edf: number;
  hora_rdf: number;
  hora_enf: number;
  hora_rnf: number;
  vaca_comun: number;
  vaca_dias_comun: number;
  vaca_compe: number;
  vaca_dias_compe: number;
  primalegal: number;
  dias_primalegal: number;
  prima_nosalarial: number;
  cesantias: number;
  interesescesantias: number;
  incapacidades: number;
  incapacidades_dias: number;
  maternidad_paternidad: number;
  maternidad_dias: number;
  licencia_remunerada: number;
  licencia_remunerada_dias: number;
  licencia_noremunerada: number;
  licencia_noremunerada_dias: number;
  bonificacion_salarial: number;
  bonificacion_nosalarial: number;
  auxilio_salarial: number;
  auxilio_nosalarial: number;
  huelga: number;
  huelga_dias: number;
  otros_salariales: number;
  otros_nosalariales: number;
  comp_ordinario: number;
  comp_extra: number;
  bono_electronico_salarial: number;
  bono_electronico_nosalarial: number;
  bono_elec_aliment_salarial: number;
  bono_elec_aliment_nosalarial: number;
  comision: number;
  pago_terceros: number;
  anticipo: number;
  dotacion: number;
  apoyo_sostenimiento: number;
  teletrabajo: number;
  bonificacion_retiro: number;
  indemnizacion: number;
  pago_reintegro: number;
  obligatorio_salud: number;
  obligatorio_pension: number;
  obligatorio_solid_pension: number;
  obligatorio_solid_subsistencia: number;
  descuento_sindicato: number;
  descuento_sancion_publica: number;
  descuento_sancion_privada: number;
  descuento_libranza: number;
  descuento_terceros: number;
  descuento_anticipos: number;
  descuento_otras_deudas: number;
  descuento_pension_volunt: number;
  descuento_retefte: number;
  descuento_ica: number;
  descuento_afc: number;
  descuento_cooperativa: number;
  descuento_embargo: number;
  descuento_plan_complementario: number;
  descuento_educacion: number;
  descuento_reintegro: number;
  descuento_deuda_empresa: number;
  tracking_id: string | null;
  fechadesde: string;
  fechahasta: string;
  nov_contractual: string;
  uuid_designer: string | null;
  nombre_empleado: string;
  total_empleados?: number;
}

export interface ComprobantesDianResponse {
  items: ComprobanteDian[];
  first: { $ref: string };
  next?: { $ref: string };
  prev?: { $ref: string };
}
